//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CmdPal.Ext.OneNote.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CmdPal.Ext.OneNote.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create colored icons for notebooks and sections.
        /// </summary>
        public static string CreateColoredIconsForNotebooksSections {
            get {
                return ResourceManager.GetString("CreateColoredIconsForNotebooksSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create notebook: &quot;{0}&quot;.
        /// </summary>
        public static string CreateNotebook {
            get {
                return ResourceManager.GetString("CreateNotebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create page: &quot;{0}&quot;.
        /// </summary>
        public static string CreatePage {
            get {
                return ResourceManager.GetString("CreatePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create section: &quot;{0}&quot;.
        /// </summary>
        public static string CreateSection {
            get {
                return ResourceManager.GetString("CreateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create section group: &quot;{0}&quot;.
        /// </summary>
        public static string CreateSectionGroup {
            get {
                return ResourceManager.GetString("CreateSectionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display unread icon.
        /// </summary>
        public static string DisplayUnreadIcon {
            get {
                return ResourceManager.GetString("DisplayUnreadIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate an item has unread changes with: •.
        /// </summary>
        public static string DisplayUnreadIconDescription {
            get {
                return ResourceManager.GetString("DisplayUnreadIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encrypted.
        /// </summary>
        public static string Encrypted {
            get {
                return ResourceManager.GetString("Encrypted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid query.
        /// </summary>
        public static string InvalidQuery {
            get {
                return ResourceManager.GetString("InvalidQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first character of the search must be a letter or a digit.
        /// </summary>
        public static string InvalidQueryDescription {
            get {
                return ResourceManager.GetString("InvalidQueryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Modified: {0:F}.
        /// </summary>
        public static string LastModified {
            get {
                return ResourceManager.GetString("LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked.
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New quick note.
        /// </summary>
        public static string NewQuickNote {
            get {
                return ResourceManager.GetString("NewQuickNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items found. Type a valid name to create one.
        /// </summary>
        public static string NoItemsFoundTypeValidName {
            get {
                return ResourceManager.GetString("NoItemsFoundTypeValidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matches found.
        /// </summary>
        public static string NoMatchesFound {
            get {
                return ResourceManager.GetString("NoMatchesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try searching something else, or syncing your notebooks..
        /// </summary>
        public static string NoMatchesFoundDescription {
            get {
                return ResourceManager.GetString("NoMatchesFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notebook names cannot contain: {0}.
        /// </summary>
        public static string NotebookNamesCannotContain {
            get {
                return ResourceManager.GetString("NotebookNamesCannotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote COM object timeout.
        /// </summary>
        public static string OneNoteComObjectTimeout {
            get {
                return ResourceManager.GetString("OneNoteComObjectTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delay in milliseconds before the OneNote COM object is removed from memory after user input. Higher values reduce the chances needed for performing the slow action of getting the COM object, but keep the COM object in memory for longer..
        /// </summary>
        public static string OneNoteComObjectTimeoutDescription {
            get {
                return ResourceManager.GetString("OneNoteComObjectTimeoutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote is not installed.
        /// </summary>
        public static string OneNoteNotInstalled {
            get {
                return ResourceManager.GetString("OneNoteNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please install OneNote to use this plugin.
        /// </summary>
        public static string OneNoteNotInstalledDescription {
            get {
                return ResourceManager.GetString("OneNoteNotInstalledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open and sync.
        /// </summary>
        public static string OpenAndSync {
            get {
                return ResourceManager.GetString("OpenAndSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in notebook explorer.
        /// </summary>
        public static string OpenInNotebookExplorer {
            get {
                return ResourceManager.GetString("OpenInNotebookExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open and sync notebooks.
        /// </summary>
        public static string OpenSyncNotebooks {
            get {
                return ResourceManager.GetString("OpenSyncNotebooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open &quot;{0}&quot; in OneNote.
        /// </summary>
        public static string OpenXInOneNote {
            get {
                return ResourceManager.GetString("OpenXInOneNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path: {0}.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searches your local OneNote notebooks. This plugin requires the OneNote desktop app which is included in Microsoft Office.
        /// </summary>
        public static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneNote.
        /// </summary>
        public static string PluginTitle {
            get {
                return ResourceManager.GetString("PluginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now searching by title..
        /// </summary>
        public static string SearchingByTitle {
            get {
                return ResourceManager.GetString("SearchingByTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now searching by title in &quot;{0}&quot;.
        /// </summary>
        public static string SearchingByTitleInX {
            get {
                return ResourceManager.GetString("SearchingByTitleInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now searching all pages in &quot;{0}&quot;.
        /// </summary>
        public static string SearchingPagesInX {
            get {
                return ResourceManager.GetString("SearchingPagesInX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;{0}&apos; to search this item. Use &apos;{1}&apos; to search by title in this item.
        /// </summary>
        public static string SearchInItemInfo {
            get {
                return ResourceManager.GetString("SearchInItemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search OneNote pages.
        /// </summary>
        public static string SearchOneNotePages {
            get {
                return ResourceManager.GetString("SearchOneNotePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section group names cannot contain: {0}.
        /// </summary>
        public static string SectionGroupNamesCannotContain {
            get {
                return ResourceManager.GetString("SectionGroupNamesCannotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section names cannot contain: {0}.
        /// </summary>
        public static string SectionNamesCannotContain {
            get {
                return ResourceManager.GetString("SectionNamesCannotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show encrypted sections.
        /// </summary>
        public static string ShowEncryptedSections {
            get {
                return ResourceManager.GetString("ShowEncryptedSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using &quot;{0}&quot; show encrypted sections, if the section has been unlocked, allow temporary access..
        /// </summary>
        public static string ShowEncryptedSectionsDescription {
            get {
                return ResourceManager.GetString("ShowEncryptedSectionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show recycle bin.
        /// </summary>
        public static string ShowRecycleBin {
            get {
                return ResourceManager.GetString("ShowRecycleBin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When using &quot;{0}&quot; show items that are in the recycle bin..
        /// </summary>
        public static string ShowRecycleBinDescription {
            get {
                return ResourceManager.GetString("ShowRecycleBinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlocked.
        /// </summary>
        public static string Unlocked {
            get {
                return ResourceManager.GetString("Unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unread.
        /// </summary>
        public static string Unread {
            get {
                return ResourceManager.GetString("Unread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View notebook explorer.
        /// </summary>
        public static string ViewNotebookExplorer {
            get {
                return ResourceManager.GetString("ViewNotebookExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; or select this option to search by notebook structure.
        /// </summary>
        public static string ViewNotebookExplorerDescription {
            get {
                return ResourceManager.GetString("ViewNotebookExplorerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View recent pages.
        /// </summary>
        public static string ViewRecentPages {
            get {
                return ResourceManager.GetString("ViewRecentPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; or select this option to see recently modified pages.
        /// </summary>
        public static string ViewRecentPagesDescription {
            get {
                return ResourceManager.GetString("ViewRecentPagesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit the Microsoft Store.
        /// </summary>
        public static string VisitMicrosoftStore {
            get {
                return ResourceManager.GetString("VisitMicrosoftStore", resourceCulture);
            }
        }
    }
}
